import {
  AlertTriangle as IconAlertTriangle,
  ArrowRight as IconArrowRight,
  Check as IconCheck,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  Command as IconCommand,
  CreditCard as IconCreditCard,
  File as IconFile,
  FileText as IconFileText,
  HelpCircle as IconHelpCircle,
  Image as IconPhoto,
  Laptop as IconDeviceLaptop,
  LayoutDashboard as IconLayoutDashboard,
  Loader2 as IconLoader2,
  LogIn as IconLogin,
  Menu as IconMenu,
  ShoppingBag as IconShoppingBag,
  Moon as IconMoon,
  MoreVertical as IconDotsVertical,
  Pizza as IconPizza,
  Plus as IconPlus,
  Settings as IconSettings,
  Sun as IconSun,
  Trash as IconTrash,
  User as IconUser,
  UserCircle as IconUserCircle,
  UserX as IconUserX,
  X as IconX,
} from "lucide-react";

import type { LucideProps } from "lucide-react";

export type Icon = React.ComponentType<LucideProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  check: IconCheck,
};
